services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=mariam
      - MINIO_ROOT_PASSWORD=mariam123
      - MINIO_DEFAULT_BUCKETS=my_bucket
    command: server /data --console-address ":9001"
    networks:
      mynet:
        aliases:
          - my_localhost
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
networks:
  mynet:
    driver: bridge
volumes:
  minio_data:
    driver: local